### ISSUE TITLE
vcloud openapi v37.2 Java generation

### ISSUE THREAD

**Issue by tvs61** [ccouzens/vcloud-rest-openapi#14]
I'm attempting to use the 37.2.json spec to generate java objects via `openapi-generator-cli-6.6.0` running under JDK11 and the resulting maven project won't build due to errors related to the "type" variable derived from the spec.  I was seeing this same issue when using the 37.0 spec as well.

In short, it appears that "type" and "_type" in the generated VcloudQueryResultRecordType class conflict.  Specifically:

```
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE) private String type;

  public static final String SERIALIZED_NAME_TYPE = "_type";
  @SerializedName(SERIALIZED_NAME_TYPE) protected String type;
```

Which results in these 3 methods being duplicated in VcloudQueryResultRecordType (once for "type" and once for "_type"):

```
  public VcloudQueryResultRecordType type(String type) {

    this.type = type;
    return this;
  }

  /**
   * Contains the type of the resource.
   * @return type
   **/
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(String type) { this.type = type; }

  public VcloudQueryResultRecordType link(List<VcloudLinkType> link) {

    this.link = link;
    return this;
```

This in-turn throws off any other generated VcloudQueryResult* classes which descend from VcloudQueryResultRecordType.    

From what I can tell, the "_type" discriminator is the root of my problems (from the spec):
```
      "vcloud_QueryResultRecordType": {
        "title": "vcloud_QueryResultRecordType",
        "description": "Base type for a single record from query result in records format. Subtypes define more specific elements.",
        "discriminator": {
          "propertyName": "_type",
```

Is there a particular option I need to provide to `openapi-generator-cli-6.6.0` to generate better/compiling Java?  I've attempted with various combinations of `discriminatorCaseSensitive`, `legacyDiscriminatorBehavior`, `x-discriminator-value`, etc - but none of those appear to make any difference in the generated output.  Perhaps I'm looking in the wrong place WRT the discriminator value?  

Thanks in advance.

**Comment by tvs61** [comment]
Perhaps I'm being dense, but after applying the patch the resulting generated code still won't compile, albeit with slightly different behavior.  

In `VcloudQueryResultRecordType` both of these remain: 
```
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_TYPE = "_type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  protected String type;
```

and various other classes are complaining that "_type cannot be resolved to a variable" as well as duplicate field/method complaints.

**Comment by mzvankovich** [comment]
> Perhaps I'm being dense, but after applying the patch the resulting generated code still won't compile, albeit with slightly different behavior.
> 
> In `VcloudQueryResultRecordType` both of these remain:
> 
> ```
>   public static final String SERIALIZED_NAME_TYPE = "type";
>   @SerializedName(SERIALIZED_NAME_TYPE)
>   private String type;
> 
>   public static final String SERIALIZED_NAME_TYPE = "_type";
>   @SerializedName(SERIALIZED_NAME_TYPE)
>   protected String type;
> ```
> 
> and various other classes are complaining that "_type cannot be resolved to a variable" as well as duplicate field/method complaints.

Hello, i've just checked the patch script. That one is not relevant any more, I'll provide working one as soon as possible.

**Comment by tvs61** [comment]
Thanks in advance.

**Comment by mzvankovich** [comment]
> Thanks in advance. Understood, that it's just temporary and I appreciate the patch.

I've updated patch scripts and README accordinly, see for details: [Known Issues](https://github.com/ccouzens/vcloud-rest-openapi#known-issues) . The patch works for a java codegenerated client only. Let me know if there are issues.
