### ISSUE TITLE
request for enhancement: make mapping values explicit schema references

### ISSUE THREAD

**Issue by jamesmanning** [ccouzens/vcloud-rest-openapi#16]
Using your 36.3 file, I hit a bug in a different tool that generates clients from openapi definitions, filed here:

https://github.com/RicoSuter/NSwag/issues/4475

This tool doesn't currently handle the mapping values being just the name of the schema, and that tool currently tries to resolve that string as an external file reference.

The [OpenApi spec very clearly allows that](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#discriminatorObject), so the bug is in that tool, but since making the values into explicit schema references (change mapping value "Foo" to "#/components/schemas/Foo") worked with that tool, I wondered if that was a possible change in the generated files here.  It seems like the more explicit schema reference option is "better" as a value since it prevents tooling from having to interpret whether the value is an external file or a schema ref, but I can understand if this isn't a desired change.

Not a bug in your openapi generation at all, just an enhancement request that would help at least one tool out there handle the generated files a little better. 😄 

Thank you @ccouzens !

**Comment by ccouzens** [comment]
Hey James,

Can you try again from this branch? https://github.com/ccouzens/vcloud-rest-openapi/tree/discriminator_issue

I've tweaked the generator and rerun it to add `#/components/schemas/Foo` to the discriminator mappings.

Thanks,
Hopefully this is useful to you,

Chris

**Comment by jamesmanning** [comment]
@ccouzens that works perfectly! Thank you so much!!
