### ISSUE TITLE
request: add support for the cloudapi/1.0.0 endpoints?

### ISSUE THREAD

**Issue by jamesmanning** [ccouzens/vcloud-rest-openapi#18]
This may already exist and I just haven't been able to find it (and if so, I apologize profusely ahead of time!), but the newer cloudapi/1.0.0 endpoint gets referred to in the existing generated openapi docs, but it doesn't seem to be covered by the generated docs itself.

https://developer.vmware.com/apis/vmware-cloud-director/v36.3/

    Notes: - This field is deprecated. Use /cloudapi/1.0.0/trustedCertificates instead.

I've tried downloading all the docs and no openapi/swagger files seem to exist that I can find.  If it's in the same category as the older /api rest api endpoint and there's no complete openapi spec, but the docs cover it, could it be generated as well, either as separate files or perhaps included in the existing generated openapi docs?

There *is* a top-level doc for the endpoint in the vcd-api-schemas repo

https://github.com/vmware/vcd-api-schemas/blob/master/schemas/openapi/src/main/resources/schemas/vcloud-openapi-schemas.yaml

After cloning the repo, though, AFAICT that doesn't include the necessary endpoints, like a POST call to sessions to login

https://developer.vmware.com/apis/vmware-cloud-director/v36.3/cloudapi/1.0.0/sessions/post/

["sessions" only shows up once in the repo AFAICT](https://github.com/search?q=repo%3Avmware%2Fvcd-api-schemas%20sessions&type=code), and it's not in reference to that call.

**Comment by ccouzens** [comment]
I wish I could help better here.

I've tried to figure it out from before. Here is an similar issue that may be contain something that helps you https://github.com/ccouzens/vcloud-rest-openapi/issues/2

---

VMware refer to the cloudapi API as `vCloud Director OpenAPI` and [the documentation](https://vdc-download.vmware.com/vmwb-repository/dcr-public/a36f68c4-9f5a-4a63-894c-eb3840773fe7/b37fc25f-f5f3-442b-b3a6-d93d38132e06/vcd-openapi-docs.html) looks like it was generated from an OpenAPI file.

I could never find a JSON or YML file for it. VMware are missing a trick not publishing machine readable documentation.

I no longer use vCloud so I don't have access to a vCloud server. I suspect each vCloud server may host the openAPI definitions, but I cannot verify this.

If you do find the OpenAPI definitions anywhere, please let me know. I'd like to add a link or instructions to help others find them

**Comment by mzvankovich** [comment]
Here's my two cents.  
I've experience working with that vcd OpenAPI and also have't managed to find any open api schema definitions. According to this [VMware Cloud Director OpenAPI](https://developer.vmware.com/apis/vmware-cloud-director/v36.3/) documentation it still _borrows some elements of the legacy VMware Cloud Director API._ That makes me think that, although REST API is provided, either a Code-First or Design-First standardized documentation is still not supported.

**Comment by jamesmanning** [comment]
Thanks guys! The /api-explorer/provider/cloudapi.json endpoint mentioned in the other issue seems to mostly work - the 36.3 version from there is attached:

[cloudapi_json.txt](https://github.com/ccouzens/vcloud-rest-openapi/files/12072174/cloudapi_json.txt)

It has a couple of missing definitions (VgpuProfileCommon and VgpuConsumerEntity) and some malformed refs (field value of "#/definitions/query.yaml#/definitions/Page" but should just be "#/definitions/Page" AFAICT) but otherwise seems to at least be valid enough to generate a client from.  Not sure how far off from the reality of the api behavior it is, but it's definitely a start!

**Comment by demitry** [comment]
For the man who could be interested today ;)
Agree with the latest comment, it is possible to generate the client and server by fixing "/definitions/definitions/" and definitions with queries
using NSwagStudio or https://editor.swagger.io

VgpuConsumerEntity is not defined in the API and documentation, and VgpuProfileCommon could be also skipped I think.
